version: "3"
services: 
    app:
        build: .
        image: quickapi
        container_name: quickapi-app
        depends_on:
            - database
            # - redis
        ports:
            - "8080:8080"
        links:
            - database:database
            # - redis:redis
        command: /start-reload.sh
        volumes:
            - ./app:/app
    database:
        container_name: quickapi-db
        image: mysql:5.7
        ports:
            - "13309:3306"
        volumes:
            - .docker/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=quickapi
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=quickapi
            - MYSQL_PASSWORD=password
        